import React, { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Save, Upload } from 'lucide-react';
import { api } from '@/config';
import { jsonBody, requestJson } from '@/lib/api';

type Config={name:string;universityName:string;campus:string;address:string;contactLine:string;title:string;body:string;footer:string;referencePrefix:string;signatoryName:string;signatoryTitle:string;signatoryDepartment:string;signatoryEmail:string;logoUrl:string;signatureUrl:string;verificationBaseUrl:string;sectionOrder:string[];showLogo:boolean;showSignature:boolean;showFooter:boolean;fontSize:number};
type Token={key:string;label:string};
const labels:Record<string,string>={header:'Letterhead',meta:'Date and reference',title:'Document title',body:'Status and letter body',signature:'Signatory',footer:'Footer'};

export function ClearanceTemplateEditor(){
 const [config,setConfig]=useState<Config|null>(null);const [tokens,setTokens]=useState<Token[]>([]);const [version,setVersion]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{requestJson('/api/clearance/template').then(data=>{setConfig(data.config);setTokens(data.tokens||[]);setVersion(data.version);}).catch(e=>setError(e.message));},[]);
 function field<K extends keyof Config>(key:K,value:Config[K]){setConfig(current=>current?{...current,[key]:value}:current);setNotice('');}
 function move(index:number,direction:-1|1){if(!config)return;const next=[...config.sectionOrder];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];field('sectionOrder',next);}
 async function save(){if(!config)return;setBusy(true);setError('');try{const data=await requestJson('/api/clearance/template',{method:'POST',...jsonBody({config})});setConfig(data.config);setVersion(data.version);setNotice(`Template version ${data.version} is now active.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function uploadSignature(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const body=new FormData();body.append('signature',file);setBusy(true);setError('');try{const data=await requestJson('/api/clearance/template/signature',{method:'POST',body});field('signatureUrl',data.signatureUrl);setNotice('Signature uploaded. Save the template to activate it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);e.target.value='';}}
 const sample=useMemo(()=>({student_name:'Sample Student',registration_number:'FA22-BCS-001',department:'Computer Science',purpose:'Degree issuance',issue_date:new Date().toLocaleDateString(),reference_number:`${config?.referencePrefix||'LIB-CLR'}-2026-000001`,university_name:config?.universityName||'',campus:config?.campus||'',address:config?.address||'',signatory_name:config?.signatoryName||'',signatory_title:config?.signatoryTitle||'',signatory_department:config?.signatoryDepartment||'',signatory_email:config?.signatoryEmail||'',active_books_count:'0',outstanding_fine:'0.00',father_name:'Sample Father',semester:'8',student_status:'Graduated',student_email:'student@example.edu',contact_number:'03000000000'}),[config]);
 const render=(text:string)=>text.replace(/{{\s*([a-z][a-z0-9_]*)\s*}}/g,(_,key)=>String((sample as Record<string,string>)[key]??`[${key}]`));
 if(!config)return <div className="bg-white border rounded-xl p-6">{error||'Loading clearance template…'}</div>;
 const textInput='w-full px-3 py-2 border rounded-lg text-sm';
 return <div className="space-y-4">
  <div className="bg-white border rounded-xl p-5 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold text-gray-800">Clearance Letter Template</h3><p className="text-xs text-gray-500 mt-1">Active version {version}. Saving creates a new version; issued PDFs remain unchanged.</p></div><button onClick={()=>void save()} disabled={busy} className="px-4 py-2 bg-blue-800 text-white rounded-lg text-sm flex items-center gap-2 disabled:opacity-50"><Save size={15}/>{busy?'Saving…':'Save new version'}</button></div>
  {error&&<p role="alert" className="p-3 bg-red-50 text-red-700 rounded-lg text-sm">{error}</p>}{notice&&<p role="status" className="p-3 bg-emerald-50 text-emerald-800 rounded-lg text-sm">{notice}</p>}
  <div className="grid xl:grid-cols-[1fr_0.9fr] gap-4">
   <div className="space-y-4">
    <section className="bg-white border rounded-xl p-5 space-y-4"><h4 className="font-medium text-gray-800">Document and letterhead</h4><div className="grid md:grid-cols-2 gap-3"><label className="text-sm">Template name<input className={textInput} value={config.name} onChange={e=>field('name',e.target.value)}/></label><label className="text-sm">Reference prefix<input className={textInput} value={config.referencePrefix} onChange={e=>field('referencePrefix',e.target.value.toUpperCase())}/></label><label className="text-sm md:col-span-2">University name<input className={textInput} value={config.universityName} onChange={e=>field('universityName',e.target.value)}/></label><label className="text-sm">Campus<input className={textInput} value={config.campus} onChange={e=>field('campus',e.target.value)}/></label><label className="text-sm">Contact line<input className={textInput} value={config.contactLine} onChange={e=>field('contactLine',e.target.value)}/></label><label className="text-sm md:col-span-2">Address<input className={textInput} value={config.address} onChange={e=>field('address',e.target.value)}/></label><label className="text-sm md:col-span-2">Verification website (optional)<input className={textInput} value={config.verificationBaseUrl} onChange={e=>field('verificationBaseUrl',e.target.value)} placeholder="https://library.example.edu"/></label></div><div className="flex gap-5 text-sm"><label><input type="checkbox" checked={config.showLogo} onChange={e=>field('showLogo',e.target.checked)}/> Show configured library logo</label><label>Body font size <input type="number" min="9" max="14" className="w-16 ml-1 border rounded px-2 py-1" value={config.fontSize} onChange={e=>field('fontSize',Number(e.target.value))}/></label></div></section>
    <section className="bg-white border rounded-xl p-5 space-y-3"><h4 className="font-medium text-gray-800">Content</h4><label className="text-sm">Document title<input className={textInput} value={config.title} onChange={e=>field('title',e.target.value)}/></label><label className="text-sm block">Letter body<textarea rows={8} className={`${textInput} mt-1`} value={config.body} onChange={e=>field('body',e.target.value)}/></label><label className="text-sm block">Footer<textarea rows={2} className={`${textInput} mt-1`} value={config.footer} onChange={e=>field('footer',e.target.value)}/></label><div><p className="text-xs font-medium text-gray-600 mb-2">Add a placeholder to the body</p><div className="flex flex-wrap gap-1.5 max-h-32 overflow-y-auto">{tokens.map(token=><button key={token.key} type="button" onClick={()=>field('body',`${config.body} {{${token.key}}}`)} className="text-[11px] px-2 py-1 bg-blue-50 text-blue-700 rounded border border-blue-100" title={token.label}>{`{{${token.key}}}`}</button>)}</div></div></section>
    <section className="bg-white border rounded-xl p-5 space-y-3"><h4 className="font-medium text-gray-800">Signatory</h4><div className="grid md:grid-cols-2 gap-3"><label className="text-sm">Name<input className={textInput} value={config.signatoryName} onChange={e=>field('signatoryName',e.target.value)}/></label><label className="text-sm">Title<input className={textInput} value={config.signatoryTitle} onChange={e=>field('signatoryTitle',e.target.value)}/></label><label className="text-sm">Department<input className={textInput} value={config.signatoryDepartment} onChange={e=>field('signatoryDepartment',e.target.value)}/></label><label className="text-sm">Email<input type="email" className={textInput} value={config.signatoryEmail} onChange={e=>field('signatoryEmail',e.target.value)}/></label></div><div className="flex flex-wrap items-center gap-3"><input id="clearance-signature" type="file" accept="image/png,image/jpeg" className="hidden" onChange={uploadSignature}/><label htmlFor="clearance-signature" className="px-3 py-2 border rounded-lg text-sm cursor-pointer flex items-center gap-2"><Upload size={15}/>Upload PNG/JPEG signature</label><label className="text-sm"><input type="checkbox" checked={config.showSignature} onChange={e=>field('showSignature',e.target.checked)}/> Show uploaded signature</label>{config.signatureUrl&&<img src={api(config.signatureUrl)} alt="Signature preview" className="h-12 max-w-40 object-contain border rounded bg-white"/>}</div></section>
    <section className="bg-white border rounded-xl p-5"><h4 className="font-medium text-gray-800 mb-3">Section order</h4><div className="divide-y border rounded-lg">{config.sectionOrder.map((key,index)=><div key={key} className="flex items-center justify-between px-3 py-2"><span className="text-sm">{index+1}. {labels[key]||key}</span><div className="flex"><button disabled={index===0} onClick={()=>move(index,-1)} className="p-2 disabled:opacity-20" aria-label={`Move ${key} up`}><ArrowUp size={14}/></button><button disabled={index===config.sectionOrder.length-1} onClick={()=>move(index,1)} className="p-2 disabled:opacity-20" aria-label={`Move ${key} down`}><ArrowDown size={14}/></button></div></div>)}</div><label className="block text-sm mt-3"><input type="checkbox" checked={config.showFooter} onChange={e=>field('showFooter',e.target.checked)}/> Show footer</label></section>
   </div>
   <div className="xl:sticky xl:top-4 h-fit"><div className="bg-white border rounded-xl p-4"><p className="text-xs font-semibold text-gray-500 uppercase mb-3">Live A4 preview</p><div className="aspect-[1/1.414] border shadow-inner bg-white p-6 text-[8px] text-gray-800 flex flex-col"><div className="text-center"><div className="flex items-center justify-center gap-3">{config.showLogo&&config.logoUrl&&<img src={api(config.logoUrl)} className="w-10 h-10 object-contain" alt="Logo"/>}<div><p className="text-sm font-bold">{config.universityName}</p><p className="font-semibold">{config.campus}</p></div></div><p>{config.address}</p><p>{config.contactLine}</p></div><div className="flex justify-between mt-6"><span>Date: {sample.issue_date}</span><span>Reference: {sample.reference_number}</span></div><h5 className="text-center font-bold underline text-xs mt-7">{config.title}</h5><p className="text-center mt-5 bg-emerald-50 border border-emerald-200 text-emerald-800 py-2 font-bold">LIBRARY CLEARANCE STATUS: CLEARED</p><div className="mt-5 whitespace-pre-wrap leading-relaxed text-justify">{render(config.body)}</div><div className="mt-auto"><div className="mb-8">{config.showSignature&&config.signatureUrl&&<img src={api(config.signatureUrl)} className="h-10 max-w-32 object-contain" alt="Signature"/>}<p className="font-bold">{config.signatoryName}</p><p>{config.signatoryTitle}</p><p>{config.signatoryDepartment}</p><p>{config.signatoryEmail}</p></div>{config.showFooter&&<p className="text-center border-t pt-2">{render(config.footer)}</p>}</div></div></div></div>
  </div>
 </div>;
}
