import { useEffect, useState } from 'react';
import { useBlocker } from 'react-router';
import { GripVertical, ArrowUp, ArrowDown, Plus, Save, Archive, RotateCcw, Columns3, LockKeyhole, Trash2 } from 'lucide-react';
import { requestJson, jsonBody } from '@/lib/api';
import type { CatalogKind, CatalogField, CatalogLayout } from '@/lib/fields';

const inputClass='w-full mt-1.5 px-3 py-2.5 rounded-lg border border-slate-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500';
const typeLabels:Record<string,string>={text:'Short text',textarea:'Long text',email:'Email address',tel:'Phone number',number:'Number',date:'Date',select:'Dropdown'};
export function FieldLayoutEditor({kind,onDirtyChange}:{kind:CatalogKind;onDirtyChange:(dirty:boolean)=>void}) {
  const [layout,setLayout]=useState<CatalogLayout|null>(null); const [saved,setSaved]=useState('');
  const [selected,setSelected]=useState(''); const [dragging,setDragging]=useState<string|null>(null);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [retry,setRetry]=useState(0);
  const dirty=!!layout && JSON.stringify(layout)!==saved;
  useEffect(()=>{const controller=new AbortController(); requestJson(`/api/settings/layouts/${kind}`,{signal:controller.signal}).then(data=>{setLayout(data);setSaved(JSON.stringify(data));setSelected(data.fields[0].key);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[kind,retry]);
  useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
  useEffect(()=>{if(!dirty)return;const before=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
  const blocker=useBlocker(dirty);
  useEffect(()=>{if(blocker.state==='blocked'){if(window.confirm('Discard unsaved layout changes?'))blocker.proceed();else blocker.reset();}},[blocker]);
  const field=layout?.fields.find(f=>f.key===selected);
  const patch=(changes:Partial<CatalogField>)=>{setNotice('');setLayout(current=>current?{...current,fields:current.fields.map(f=>f.key===selected?{...f,...changes}:f)}:current);};
  function move(key:string,to:number) {setLayout(current=>{if(!current)return current;const fields=[...current.fields];const from=fields.findIndex(f=>f.key===key);if(from<0 || to<0 || to>=fields.length)return current;fields.splice(to,0,fields.splice(from,1)[0]);return {...current,fields};});setNotice('');}
  function add() {const key=`custom_${crypto.randomUUID().replaceAll('-','')}`;setLayout(current=>current?{...current,fields:[...current.fields,{key,label:'New field',type:'text',core:false,required:false,showInForm:true,showInTable:true,width:'half',archived:false,options:[],aliases:[]}]}:current);setSelected(key);setNotice('');}
  function removeField() {if(!layout||!field||field.core)return;if(!window.confirm(`Delete “${field.label}”? Saving the layout will permanently remove this field and all of its saved values from every ${kind==='students'?'student':'book'} record.`))return;const index=layout.fields.findIndex(item=>item.key===field.key);const fields=layout.fields.filter(item=>item.key!==field.key);setLayout({...layout,fields});setSelected(fields[Math.min(index,fields.length-1)]?.key||'');setNotice('Field marked for permanent deletion. Save the layout to apply it.');}
  async function save() {if(!layout)return;setBusy(true);setError('');setNotice('');try{const data=await requestJson(`/api/settings/layouts/${kind}`,{method:'PUT',...jsonBody(layout)});setLayout(data);setSaved(JSON.stringify(data));setNotice('Layout saved. Forms, tables, and CSV templates now use these fields.');window.dispatchEvent(new Event('layout-updated'));localStorage.setItem('library_layout_updated',String(Date.now()));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const essential=field?.core && (kind==='students'?['name','registration_no']:['title','accession_no']).includes(field.key);
  return <div className="space-y-4 min-w-0">
    <div className="rounded-xl border bg-white p-5 flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-blue-800"><Columns3 size={20}/><h2 className="font-semibold capitalize">{kind} layout</h2></div><p className="text-sm text-slate-500 mt-2 max-w-xl">Arrange fields to match your library. Drag the handle or use the arrows, then save your layout.</p></div><button disabled={!dirty||busy} onClick={save} className="flex items-center gap-2 bg-blue-800 text-white px-4 py-2.5 rounded-lg text-sm disabled:opacity-40"><Save size={16}/>{busy?'Saving…':'Save layout'}</button></div>
    {error&&<div role="alert" className="p-4 rounded-lg bg-red-50 text-red-700 text-sm">{error} <button disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved layout changes and load the latest version?')){setLayout(null);setRetry(v=>v+1);}}} className="underline ml-2">Reload latest layout</button></div>}
    {notice&&<p role="status" className="p-4 rounded-lg bg-emerald-50 text-emerald-800 text-sm">{notice}</p>}
    {!layout&&!error&&<p className="p-6 text-slate-500">Loading layout…</p>}
    {layout&&<fieldset disabled={busy} className="min-w-0 space-y-4">
      <div className="flex flex-wrap gap-3 items-center text-xs text-slate-500"><span className="rounded-full px-3 py-1 bg-blue-50 text-blue-800">{layout.fields.filter(f=>!f.archived).length} active fields</span><span>{layout.fields.filter(f=>!f.archived&&f.showInTable).length} table columns</span><span>{dirty?'Unsaved changes':`Saved · Version ${layout.revision}`}</span>{dirty&&<button onClick={()=>{setLayout(JSON.parse(saved));setError('');setNotice('');setSelected(JSON.parse(saved).fields[0].key);}} className="underline">Discard changes</button>}</div>
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 items-start">
        <section className="bg-white border rounded-xl overflow-hidden"><div className="p-4 border-b flex items-center justify-between"><h3 className="text-sm font-semibold">Field order</h3><button disabled={layout.fields.length>=50} onClick={add} className="flex gap-1 items-center text-sm text-blue-800 disabled:opacity-40"><Plus size={16}/>Add field</button></div>
          <ol className="divide-y max-h-[640px] overflow-y-auto">{layout.fields.map((f,index)=><li key={f.key} data-field-key={f.key} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move';}} onDrop={e=>{e.preventDefault();const key=e.dataTransfer.getData('text/plain')||dragging;if(key)move(key,index);setDragging(null);}} className={`flex items-center gap-1 p-2.5 ${selected===f.key?'bg-blue-50 ring-1 ring-inset ring-blue-200':''} ${f.archived?'opacity-60':''} ${dragging===f.key?'opacity-40':''}`}>
            <span role="button" tabIndex={0} draggable onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();move(f.key,index+(e.key==='ArrowUp'?-1:1));}}} onDragStart={e=>{setDragging(f.key);e.dataTransfer.setData('text/plain',f.key);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setDragging(null)} aria-label={`Drag ${f.label}`} className="p-1.5 cursor-grab text-slate-400"><GripVertical size={18} className="pointer-events-none"/></span>
            <button onClick={()=>setSelected(f.key)} className="flex-1 min-w-0 text-left px-1 py-1"><span className="text-sm font-medium text-slate-800 break-words">{f.label||'Untitled field'}</span><span className="block text-xs text-slate-500 mt-1">{f.archived?'Archived':`${typeLabels[f.type]}${f.required?' · Required':''}${f.showInTable?' · Table':''}`}</span></button>
            <span className="text-xs text-slate-400 mr-1">{index+1}</span><div className="flex flex-col"><button disabled={index===0} onClick={()=>move(f.key,index-1)} aria-label={`Move ${f.label} up`} className="p-1 text-slate-500 disabled:opacity-20"><ArrowUp size={15}/></button><button disabled={index===layout.fields.length-1} onClick={()=>move(f.key,index+1)} aria-label={`Move ${f.label} down`} className="p-1 text-slate-500 disabled:opacity-20"><ArrowDown size={15}/></button></div>
          </li>)}</ol></section>
        {field&&<section className="bg-white border rounded-xl p-5 space-y-5"><div><h3 className="font-semibold text-sm">Edit field</h3><p className="text-xs text-slate-500 mt-1">Changes apply after you save the layout.</p></div>
          <label className="block text-sm text-slate-700">Column name<input aria-label="Column name" maxLength={80} value={field.label} onChange={e=>patch({label:e.target.value})} className={inputClass}/></label>
          <label className="block text-sm text-slate-700">Field type<select aria-label="Field type" disabled={field.core} value={field.type} onChange={e=>patch({type:e.target.value,options:e.target.value==='select'?['Option 1']:[]})} className={`${inputClass} disabled:bg-slate-50`}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
          {field.type==='select'&&<label className="block text-sm text-slate-700">Dropdown options (one per line)<textarea disabled={field.core} aria-label="Dropdown options" value={field.options.join('\n')} onChange={e=>patch({options:e.target.value.split('\n')})} rows={4} className={inputClass}/></label>}
          <div className="space-y-3 text-sm">{([{key:'required',label:'Required when adding or editing',disabled:essential},{key:'showInForm',label:'Show in add and edit forms',disabled:essential||field.required},{key:'showInTable',label:'Show in the catalog table',disabled:false}] as const).map(({key,label,disabled})=><label className="flex items-center gap-3" key={key}><input type="checkbox" disabled={disabled||field.archived} checked={field[key]} onChange={e=>patch({[key]:e.target.checked,...(key==='required'&&e.target.checked?{showInForm:true}:{})})} className="accent-blue-800 w-4 h-4"/>{label}</label>)}</div>
          <label className="block text-sm text-slate-700">Form width<select aria-label="Form width" value={field.width} onChange={e=>patch({width:e.target.value as 'half'|'full'})} className={inputClass}><option value="half">Half row</option><option value="full">Full row</option></select></label>
          {field.core?<p className="flex items-start gap-2 text-xs text-slate-500 bg-slate-50 rounded-lg p-3"><LockKeyhole size={16} className="shrink-0"/>Built-in field. Its data type and identity rules support borrowing and imports. Labels and order are editable.</p>:<div className="border-t pt-4 space-y-3"><div className="flex flex-wrap gap-4"><button onClick={()=>patch({archived:!field.archived})} className="flex items-center gap-2 text-sm text-blue-800">{field.archived?<RotateCcw size={16}/>:<Archive size={16}/>} {field.archived?'Restore field':'Archive field'}</button><button onClick={removeField} className="flex items-center gap-2 text-sm text-red-700"><Trash2 size={16}/>Delete field</button></div><p className="text-xs text-slate-500">Archive hides a field and keeps its values. Delete permanently removes the field and its values after you save.</p></div>}
        </section>}
      </div>
      <section className="bg-white border rounded-xl p-5"><h3 className="text-sm font-semibold">Table preview</h3><p className="text-xs text-slate-500 mt-1 mb-4">Visible columns, in their saved order. Row numbers and record actions stay at the edges.</p><div className="overflow-x-auto rounded-lg border"><div className="flex w-max min-w-full bg-slate-50 text-xs font-medium text-slate-700"><span className="px-4 py-3">Sr #</span>{layout.fields.filter(f=>f.showInTable&&!f.archived).map(f=><span key={f.key} className="px-4 py-3 border-l">{f.label}</span>)}{kind==='books'&&<span className="px-4 py-3 border-l">Availability</span>}<span className="px-4 py-3 border-l">Actions</span></div></div></section>
    </fieldset>}
  </div>;
}
