// Existing tables are preserved. Additive migrations run before API readiness.
module.exports = [
  "\n      CREATE TABLE IF NOT EXISTS students (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        name VARCHAR(255) NOT NULL,\n        father_name VARCHAR(255) DEFAULT '',\n        registration_no VARCHAR(100) UNIQUE NOT NULL,\n        department VARCHAR(150) DEFAULT '',\n        contact_no VARCHAR(100) DEFAULT '',\n        semester VARCHAR(50) DEFAULT '',\n        status VARCHAR(50) DEFAULT 'Active',\n        remarks TEXT\n      )\n    ",
  "\n      CREATE TABLE IF NOT EXISTS books (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        accession_no VARCHAR(100) UNIQUE NOT NULL,\n        author_name VARCHAR(255) DEFAULT '',\n        title VARCHAR(255) NOT NULL,\n        total_copies INT NOT NULL DEFAULT 1,\n        catalog_identity CHAR(64) NULL,\n        publisher VARCHAR(255) DEFAULT '',\n        publish_year VARCHAR(20) DEFAULT '',\n        pages INT DEFAULT 0,\n        call_no VARCHAR(100) DEFAULT '',\n        binding VARCHAR(100) DEFAULT '',\n        source VARCHAR(100) DEFAULT '',\n        cost DECIMAL(10,2) DEFAULT 0,\n        isbn VARCHAR(100) DEFAULT '',\n        remarks TEXT,\n        UNIQUE KEY uq_books_catalog_identity (catalog_identity)\n      )\n    ",
  "\n      CREATE TABLE IF NOT EXISTS issues (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        student_id INT NOT NULL,\n        book_id INT NOT NULL,\n        issue_date DATE NOT NULL,\n        due_date DATE NOT NULL,\n        returned TINYINT(1) NOT NULL DEFAULT 0,\n        return_date DATE NULL,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,\n        FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE\n      )\n    ",
  "\n      CREATE TABLE IF NOT EXISTS fines (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        issue_id INT NULL,\n        student_id INT NOT NULL,\n        book_id INT NULL,\n        days_late INT NOT NULL DEFAULT 0,\n        fine_amount DECIMAL(10,2) NOT NULL DEFAULT 0,\n        fine_type ENUM('auto','manual') NOT NULL DEFAULT 'auto',\n        reason VARCHAR(500) NOT NULL DEFAULT '',\n        status ENUM('unsent','sent') NOT NULL DEFAULT 'unsent',\n        sentToAccounts TINYINT(1) DEFAULT 0,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE SET NULL,\n        FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,\n        FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE SET NULL\n      )\n    ",
  "\n      CREATE TABLE IF NOT EXISTS admins (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        email VARCHAR(255) UNIQUE NOT NULL,\n        password_hash VARCHAR(255) NOT NULL,\n        name VARCHAR(100) NOT NULL DEFAULT 'Administrator',\n        failed_attempts INT DEFAULT 0,\n        locked_until DATETIME NULL,\n        twofa_enabled TINYINT(1) DEFAULT 0,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n      )\n    ",
  "\n      CREATE TABLE IF NOT EXISTS settings (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        setting_key VARCHAR(100) UNIQUE NOT NULL,\n        setting_value TEXT,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP\n      )\n    ",
  "\n      CREATE TABLE IF NOT EXISTS fine_deletions (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        fine_id INT NOT NULL,\n        student_id INT NOT NULL,\n        book_id INT NULL,\n        issue_id INT NULL,\n        fine_amount DECIMAL(10,2) NOT NULL,\n        days_late INT NOT NULL DEFAULT 0,\n        fine_type VARCHAR(20) NOT NULL,\n        reason VARCHAR(500) NOT NULL DEFAULT '',\n        original_status VARCHAR(20) NOT NULL DEFAULT 'unsent',\n        sent_to_accounts TINYINT(1) NOT NULL DEFAULT 0,\n        resolution_status VARCHAR(20) NOT NULL DEFAULT 'pending',\n        resolved_at DATETIME NULL,\n        resolved_by INT NULL,\n        resolution_reason VARCHAR(500) NOT NULL DEFAULT '',\n        original_created_at DATETIME NULL,\n        student_registration_no VARCHAR(100) NOT NULL DEFAULT '',\n        student_name VARCHAR(255) NOT NULL DEFAULT '',\n        book_accession_no VARCHAR(100) NOT NULL DEFAULT '',\n        book_title VARCHAR(255) NOT NULL DEFAULT '',\n        deleted_by INT NOT NULL,\n        deleted_by_name VARCHAR(100) NOT NULL DEFAULT '',\n        deleted_by_email VARCHAR(255) NOT NULL DEFAULT '',\n        deletion_reason VARCHAR(500) NOT NULL,\n        deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        expires_at DATETIME NULL,\n        INDEX idx_fine_deletions_fine_id (fine_id),\n        INDEX idx_fine_deletions_expires_at (expires_at)\n      )\n    "
  ,"\n      CREATE TABLE IF NOT EXISTS clearance_templates (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        name VARCHAR(100) NOT NULL,\n        version INT NOT NULL,\n        config_json LONGTEXT NOT NULL,\n        is_active TINYINT(1) NOT NULL DEFAULT 0,\n        created_by INT NULL,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        UNIQUE KEY uq_clearance_template_version (version),\n        INDEX idx_clearance_template_active (is_active)\n      )\n    "
  ,"\n      CREATE TABLE IF NOT EXISTS clearance_sequences (\n        sequence_year VARCHAR(4) PRIMARY KEY,\n        next_number INT NOT NULL DEFAULT 1\n      )\n    "
  ,"\n      CREATE TABLE IF NOT EXISTS clearance_letters (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        reference_no VARCHAR(80) UNIQUE NOT NULL,\n        student_id INT NOT NULL,\n        student_name VARCHAR(255) NOT NULL,\n        registration_no VARCHAR(100) NOT NULL,\n        purpose VARCHAR(150) NOT NULL,\n        status ENUM('issued','revoked') NOT NULL DEFAULT 'issued',\n        student_snapshot LONGTEXT NOT NULL,\n        clearance_snapshot LONGTEXT NOT NULL,\n        template_snapshot LONGTEXT NOT NULL,\n        template_version INT NOT NULL,\n        generated_by INT NOT NULL,\n        generated_by_name VARCHAR(100) NOT NULL DEFAULT '',\n        generated_by_email VARCHAR(255) NOT NULL DEFAULT '',\n        issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        revoked_at DATETIME NULL,\n        revoked_by INT NULL,\n        revocation_reason VARCHAR(500) NOT NULL DEFAULT '',\n        pdf_data LONGBLOB NOT NULL,\n        pdf_sha256 CHAR(64) NOT NULL,\n        INDEX idx_clearance_student (student_id),\n        INDEX idx_clearance_status (status),\n        FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT\n      )\n    "
];
