const assert=require('node:assert/strict');
module.exports=async(t,{base,db})=>{
  const bcrypt=require('bcryptjs'); const password='LayoutTestPassword123!';
  await db.promise().query('INSERT INTO admins(email,password_hash,name) VALUES (?,?,?)',['layout@example.edu',await bcrypt.hash(password,10),'Layout Admin']);
  let token,layout,bookLayout,studentId;
  async function request(path,method='GET',body,authorized=true){const response=await fetch(base+path,{method,headers:{...(body instanceof FormData?{}:{'Content-Type':'application/json'}),...(authorized&&token?{Authorization:`Bearer ${token}`}:{})},...(body===undefined?{}:{body:body instanceof FormData?body:JSON.stringify(body)})});return{status:response.status,data:await response.json()};}
  async function save(kind,fields,revision){return request(`/api/settings/layouts/${kind}`,'PUT',{fields,revision});}
  async function csv(kind,text,preview=false,revision){const body=new FormData();body.append('file',new Blob([text]),'layout.csv');return request(`/api/${kind}/import?preview=${preview}${revision===undefined?'':`&revision=${revision}`}`,'POST',body);}
  const custom={key:'custom_campus001',label:'Campus',type:'select',core:false,required:true,showInForm:true,showInTable:true,width:'half',archived:false,options:['North','South'],aliases:[]};
  await t.test('only authenticated administrators can read or modify layouts',async()=>{let r=await request('/api/settings/layouts/students');assert.equal(r.status,401);r=await request('/api/auth/login','POST',{email:'layout@example.edu',password},false);assert.equal(r.status,200);token=r.data.token;r=await request('/api/settings/layouts/students');assert.equal(r.status,200);layout=r.data;assert.equal((await request('/api/settings/layouts/students','PUT',layout,false)).status,401);});
  await t.test('renamed, reordered and custom fields persist with a new revision',async()=>{const fields=[custom,...layout.fields.map(f=>f.key==='registration_no'?{...f,label:'University Roll'}:f)];const r=await save('students',fields,layout.revision);assert.equal(r.status,200,JSON.stringify(r.data));layout=r.data;assert.equal(layout.fields[0].key,custom.key);const latest=await request('/api/settings/layouts/students');assert.deepEqual(latest.data,layout);});
  await t.test('stale administrators cannot overwrite a newer layout',async()=>{const r=await save('students',layout.fields,layout.revision-1);assert.equal(r.status,409);assert.equal(r.data.code,'layout_changed');});
  await t.test('reserved names, ambiguous CSV aliases, and removed core fields are rejected',async()=>{for(const fields of [layout.fields.map(f=>f.key===custom.key?{...f,label:'Roll Number'}:f),layout.fields.map(f=>f.key===custom.key?{...f,label:'ID'}:f),layout.fields.filter(f=>f.key!=='name')])assert.equal((await save('students',fields,layout.revision)).status,400);});
  await t.test('custom required/dropdown validation applies to manual additions',async()=>{let r=await request('/api/students','POST',{name:'Layout Student',registration_no:'LAYOUT1'});assert.equal(r.status,400);r=await request('/api/students','POST',{name:'Layout Student',registration_no:'LAYOUT1',[custom.key]:'East'});assert.equal(r.status,400);r=await request('/api/students','POST',{name:'Layout Student',registration_no:'LAYOUT1',[custom.key]:'North',layoutRevision:layout.revision});assert.equal(r.status,201);studentId=r.data.id;});
  await t.test('existing core and custom values survive partial edits',async()=>{const r=await request(`/api/students/${studentId}`,'PUT',{remarks:'Updated'});assert.equal(r.status,200);const [rows]=await db.promise().query('SELECT * FROM students WHERE id=?',[studentId]);assert.equal(rows[0].name,'Layout Student');assert.equal(JSON.parse(rows[0].custom_data)[custom.key],'North');});
  await t.test('new required columns are included in CSV template and import validation',async()=>{const template=await(await fetch(base+'/api/students/template.csv',{headers:{Authorization:`Bearer ${token}`}})).text();assert(template.indexOf('Campus')<template.indexOf('Name'));assert(template.includes('University Roll'));assert.equal((await csv('students','Name,Registration No.\nMissing,LAYOUT2')).status,400);const r=await csv('students','Campus,Name,University Roll\nSouth,CSV Layout,LAYOUT2\nEast,Invalid,LAYOUT3');assert.equal(r.data.counts.added,1);assert.equal(r.data.counts.invalid,1);});
  await t.test('unknown headings cannot silently discard imported data',async()=>{const r=await csv('students','Campus,Name,University Roll,Typo field\nNorth,Unknown,LAYOUT4,Lost');assert.equal(r.status,400);});
  await t.test('legacy CSV headings remain recognized after renaming',async()=>{const r=await csv('students','Campus,Name,Registration No.\nNorth,Old Header,LAYOUT5');assert.equal(r.data.counts.added,1);});
  await t.test('incompatible custom type/options changes preserve existing data',async()=>{assert.equal((await save('students',layout.fields.map(f=>f.key===custom.key?{...f,type:'number'}:f),layout.revision)).status,400);assert.equal((await save('students',layout.fields.map(f=>f.key===custom.key?{...f,options:['South']}:f),layout.revision)).status,400);});
  await t.test('archive, edit, and restore preserve custom values and reject stale forms/previews',async()=>{const preview=await csv('students','Campus,Name,University Roll\nNorth,Stale Preview,LAYOUT6',true);let r=await save('students',layout.fields.map(f=>f.key===custom.key?{...f,archived:true}:f),layout.revision);assert.equal(r.status,200);layout=r.data;assert.equal((await request(`/api/students/${studentId}`,'PUT',{remarks:'Stale',layoutRevision:layout.revision-1})).status,409);assert.equal((await csv('students','Campus,Name,University Roll\nNorth,Stale Preview,LAYOUT6',false,preview.data.layoutRevision)).status,409);assert.equal((await request(`/api/students/${studentId}`,'PUT',{remarks:'Archived edit'})).status,200);r=await save('students',layout.fields.map(f=>f.key===custom.key?{...f,archived:false}:f),layout.revision);layout=r.data;const [rows]=await db.promise().query('SELECT custom_data FROM students WHERE id=?',[studentId]);assert.equal(JSON.parse(rows[0].custom_data)[custom.key],'North');});
  await t.test('exports use custom labels and include custom stored values',async()=>{const text=await(await fetch(base+'/api/backup/students.csv',{headers:{Authorization:`Bearer ${token}`}})).text();assert(text.includes('Campus'));assert(text.includes('University Roll'));assert(text.includes('North'));});
  await t.test('custom values can be searched in the student catalog',async()=>{const r=await request('/api/students?search=North');assert.equal(r.status,200);assert(r.data.rows.some(row=>row.id===studentId));});
  await t.test('book layouts support numeric zero, dates, CSV imports and copy conflicts',async()=>{bookLayout=(await request('/api/settings/layouts/books')).data;const shelf={...custom,key:'custom_shelf001',label:'Shelf',type:'number',required:false,options:[]};const acquired={...shelf,key:'custom_date0001',label:'Acquired',type:'date'};let r=await save('books',[shelf,acquired,...bookLayout.fields],bookLayout.revision);assert.equal(r.status,200);bookLayout=r.data;assert.equal((await csv('books','Shelf,Acquired,Accession No.,Title\n0,2026-02-30,LAYOUTB0,Invalid Date')).data.counts.invalid,1);r=await csv('books','Shelf,Acquired,Accession No.,Title\n0,2026-02-28,LAYOUTB1,Custom Book');assert.equal(r.data.counts.added,1);r=await csv('books','Shelf,Acquired,Accession No.,Title\n1,2026-02-28,LAYOUTB1,Custom Book');assert.equal(r.data.counts.conflict,1);const [rows]=await db.promise().query("SELECT custom_data FROM books WHERE accession_no='LAYOUTB1'");assert.equal(JSON.parse(rows[0].custom_data).custom_shelf001,0);});
  await t.test('return lookup accepts normalized roll/accession numbers and keeps policy behavior',async()=>{let r=await request('/api/issue','POST',{registration_no:'LAYOUT1',accession_no:'LAYOUTB1'});assert.equal(r.status,201);r=await request('/api/return/issues/student/layout1');assert.equal(r.status,200);assert.equal(r.data.records.length,1);r=await request('/api/return/issues/book/layoutb1');assert.equal(r.data.records.length,1);r=await request(`/api/return/return/${r.data.records[0].issueId}`,'POST',{});assert.equal(r.status,200);assert.equal(r.data.fineGenerated,false);});
  await t.test('manual fines move to searchable 90-day trash with a complete snapshot',async()=>{let r=await request('/api/fines/create','POST',{registration_no:'LAYOUT1',fine_amount:250,reason:'Noise in library'});assert.equal(r.status,201);const id=r.data.id;r=await request('/api/fines/unsent');const fine=r.data.find(row=>row.id===id);assert.equal(fine.fine_type,'manual');assert.equal(fine.reason,'Noise in library');r=await request('/api/notifications/recent-fines');assert(r.data.some(row=>row.id===id&&row.registrationNo==='LAYOUT1'&&row.fineAmount===250));assert.equal((await request(`/api/fines/${id}/trash`,'POST',{reason:'Entered by mistake'},false)).status,401);assert.equal((await request(`/api/fines/${id}/trash`,'POST',{reason:'x'})).status,400);r=await request(`/api/fines/${id}/trash`,'POST',{reason:'Entered by mistake'});assert.equal(r.status,200);assert.equal(r.data.retentionDays,90);assert.equal((await request('/api/fines/unsent')).data.some(row=>row.id===id),false);r=await request('/api/fines/trash?search=LAYOUT1');const deleted=r.data.rows.find(row=>row.fineId===id);assert(deleted);assert.equal(deleted.deletionReason,'Entered by mistake');assert.equal(deleted.studentName,'Layout Student');assert.equal(deleted.registrationNo,'LAYOUT1');assert.equal(deleted.fineAmount,250);assert.equal(deleted.fineType,'manual');assert.equal(deleted.originalStatus,'unsent');assert.equal(deleted.deletedByName,'Layout Admin');assert(deleted.daysRemaining>=89&&deleted.daysRemaining<=90);});
  await t.test('sent fines retain the Accounts handoff when moved to trash',async()=>{let r=await request('/api/fines/create','POST',{registration_no:'LAYOUT1',fine_amount:125,reason:'Damaged book'});const id=r.data.id;assert.equal((await request('/api/fines/send-to-account','POST',{})).status,200);r=await request('/api/reports/monthly-fines');assert(r.data.some(row=>Number(row.manual)>=125));r=await request('/api/reports/accounts-office');assert(r.data.some(row=>row.fineReason==='Damaged book'));r=await request('/api/reports/analytics');assert(Number(r.data.sentFines)>=125);assert.equal(Object.hasOwn(r.data,'collectedFines'),false);r=await request(`/api/fines/${id}/trash`,'POST',{reason:'Incorrect fine sent to Accounts'});assert.equal(r.status,200);r=await request('/api/fines/trash?search=LAYOUT1');const deleted=r.data.rows.find(row=>row.fineId===id);assert.equal(deleted.originalStatus,'sent');assert.equal(deleted.sentToAccounts,1);});
  await t.test('expired trash records are purged automatically on access',async()=>{const [rows]=await db.promise().query('SELECT id,fine_id FROM fine_deletions ORDER BY id LIMIT 1');assert(rows.length);await db.promise().query('UPDATE fine_deletions SET expires_at=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 1 SECOND) WHERE id=?',[rows[0].id]);const r=await request('/api/fines/trash');assert.equal(r.status,200);const [expired]=await db.promise().query('SELECT id FROM fine_deletions WHERE id=?',[rows[0].id]);assert.equal(expired.length,0);});
  await t.test('all business APIs reject signed-out access',async()=>{for(const path of ['/api/students','/api/books','/api/student/LAYOUT1','/api/return/issues/student/LAYOUT1','/api/dashboard/stats','/api/reports/analytics','/api/issued-students','/api/fines/unsent','/api/notifications/recent-fines','/api/reminders/overdue'])assert.equal((await request(path,'GET',undefined,false)).status,401,path);assert.equal((await request('/api/settings','POST',{finePerDay:20},false)).status,401);assert.equal((await request('/api/reminders/send','POST',undefined,false)).status,401);const backup=await fetch(base+'/api/backup/sql');assert.equal(backup.status,401);});
  await t.test('authenticated SQL backup contains restorable data and deletion audit',async()=>{const response=await fetch(base+'/api/backup/sql',{headers:{Authorization:`Bearer ${token}`}});assert.equal(response.status,200);const text=await response.text();assert(text.includes('START TRANSACTION;'));assert(text.includes('`fine_deletions`'));assert(text.includes('COMMIT;'));});
  await t.test('administrators can create and remove another login without exposing hashes',async()=>{let r=await request('/api/auth/admins');assert(r.data.every(admin=>!Object.hasOwn(admin,'password_hash')));r=await request('/api/auth/admins','POST',{name:'Second Librarian',email:'second@example.edu',password:'SecondLibraryPassword123!'});assert.equal(r.status,201);const id=r.data.admin.id;const login=await request('/api/auth/login','POST',{email:'second@example.edu',password:'SecondLibraryPassword123!'},false);assert.equal(login.status,200);assert.equal((await request(`/api/auth/admins/${id}`,'DELETE')).status,200);assert.equal((await request('/api/auth/login','POST',{email:'second@example.edu',password:'SecondLibraryPassword123!'},false)).status,401);assert.equal((await request(`/api/auth/admins/${JSON.parse(Buffer.from(token.split('.')[1],'base64url')).id}`,'DELETE')).status,409);});
  await t.test('account changes require current password and invalidate old sessions',async()=>{let r=await request('/api/auth/account','PUT',{email:'updated@example.edu',currentPassword:'Wrong',password:'NewLayoutPassword123!'});assert.equal(r.status,400);r=await request('/api/auth/account','PUT',{email:'updated@example.edu',currentPassword:password,password:'NewLayoutPassword123!'});assert.equal(r.status,200);assert.equal((await save('books',bookLayout.fields,bookLayout.revision)).status,401);r=await request('/api/auth/login','POST',{email:'updated@example.edu',password:'NewLayoutPassword123!'},false);assert.equal(r.status,200);token=r.data.token;assert.equal((await save('books',bookLayout.fields,bookLayout.revision)).status,200);});
  // Leave defaults for the reusable browser fixture, preserving custom values.
  for(const kind of ['students','books']){const fields=require('../lib/fieldSchema').defaults(kind);await db.promise().query('UPDATE catalog_layouts SET fields=?,revision=revision+1 WHERE kind=?',[JSON.stringify(fields),kind]);}
};
